[tool.bumpversion]

commit = true
tag = true
tag_name = "v{new_version}"
current_version = "1.2.1"

[[tool.bumpversion.files]]
glob = "**/*.md"

[[tool.bumpversion.files]]
filename = "colorizer_data/types.py"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "documentation/getting_started_guide/requirements.txt"
