[tool.bumpversion]

commit = true
tag = true
tag_name = "v{new_version}"
current_version = "1.2.0"

[[tool.bumpversion.files]]
glob = "**/*.md"

[[tool.bumpversion.files]]
filename = "colorizer_data/types.py"
